# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5be6522f669a01235bf46b6485d0d4084b23130d208fc78852e4b74b1fc2af5a9a8cc354adcd9b6f0bbb89e2402f4e2ba30071c1fbd21490feec3fabce2eaadb

test:
  secret_key_base: ee8474becbd59af2d9e1fb4157205418c580a8dfba983e8eb91e2ed956d8a2158967da207c7995cea9627810285d507dd33ff90198c24958dec4ea7df9efd07b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
